[package]
name = "spectro-rust"
version = "0.1.0"
edition = "2024"
description = "live spectrogram visualizer"
repository = "https://github.com/sazonek/spectro-rust"
license = "MIT"

[dependencies]
ctrlc = "3.4.7"
ws2818-rgb-led-spi-driver = "2.0.0"
